name: Bunny.net Storage Upload

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      
      - name: FTP dir upload
        uses: willfurstenau/ftp-dir-upload@main
        with:
          host: ftp.myhost.com
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./dist
          remote-dir: /